### ISSUE TITLE
List of airlines with size charts

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#1]
## Value proposition

As an airplane traveller
I want a quick overview of airlines with allowed luggage dimensions
So that I can see which airlines are unproblematic with big or many bags in hand luggage

## Description

![Image](https://user-images.githubusercontent.com/20736983/251380721-60ed6d7d-2a53-4406-99b0-2720e837b316.png)

## Acceptance criteria

- [ ] All major airlines should be listed
- [ ] Personal item and cabin bag need to be displayed in each airline
- [ ] There needs to be an indicator if a cabin bag requires a surcharge (boolean for true and false)
- [ ] The view should include a header (which will later be turned into a nav bar)

## Tasks

- [ ] Create an array with data that includes airlines and their hand luggage allowances, and sizes
- [ ] Create the list component to display the array above
- [ ] Add a graphical element to highlight cabin bag surcharge
- [ ] Create a header
- [ ] Create a test to see if the list is loaded in full

**Comment by vaupunkt** [comment]
lgtm :)
