### ISSUE TITLE
Theme selection

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#14]
## Value proposition

As an airplane traveller
I want a feature that allows choosing between light or dark mode
So that I can have a theme that is more pleasant to the eyes depending on my screen or mood

## Description
![Image](https://user-images.githubusercontent.com/20736983/255191290-a0ea1f71-a660-4824-9bfb-2e4e956e74b9.png)

## Acceptance criteria
- [ ] option 1: system setting (default)
- [ ] option 2: light mode
- [ ] option 3: dark mode

## Tasks
- [ ] create dark mode styling
- [ ] create a state for saving the user choice
- [ ] create buttons to save and activate the appropriate style

**Comment by ekat-br** [comment]
Hi @makitango  your user story is understandable to me 🙌 Perhaps you could describe more clearly in the acceptance criteria how to activate the dark mode. According to your picture, as a user I first have to go into the settings and can change the appearance there. Your settings can be accessed probably via the navigation. Is that correct?

**Comment by makitango** [comment]
> According to your picture, as a user I first have to go into the settings and can change the appearance there. Your settings can be accessed probably via the navigation. Is that correct?

Actually that was thought to be the result later on. I am currently just implementing "pure" features and they get piled up on my homepage. Once I am done with all of them, I want to create two separate sub-pages, and one for dedicated sites.

I hope that clears up the confusion, but it's very understandable coming from this picture. ;)
