### ISSUE TITLE
Sort function

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#2]
## Value proposition

As an airplane traveller
I want a feature that allows sorting by bag dimensions, either personal item or cabin bag as a reference
So that I see instantly how much I can pack depending on whether I travel light or focus on cabin bag

## Description

![Image](https://user-images.githubusercontent.com/20736983/251472923-bf0f3fce-52db-4c04-8b83-154664bc68b2.png)
![Image](https://user-images.githubusercontent.com/20736983/251475368-c0b2589a-f3fe-4f6d-ab0f-aa5c556b2107.png)

## Acceptance criteria

- [ ] The maximum allowed size for cabin bag is highlighted in green (either IATA or EU maximum)
- [ ] Above average sizes for personal item are highlighted in green

## Tasks

- [ ] Create a mapping for the list in the array to sort by either cabin bag or personal item
- [ ] Create a button to access the sort menu
- [ ] Create a button to leave the sort menu and apply the changes

**Comment by makitango** [comment]
Minor tweaks:
- discarded coloring effect since this will be specific to the overall volume anyways
- no confirmation button for changing settings needed, and intended for a latter US
