### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#3]
## Value proposition

As an airplane traveller
I want a settings page
So I have access to dark mode, metric/imperial sizes and have an info section about the app (version, developer, copyright etc)

## Description
![Image](https://user-images.githubusercontent.com/20736983/251484586-d9d74839-9abd-49fc-8384-eef3f8be489d.png)

## Acceptance criteria

- [ ] It should have to separate selection fields for each function

## Tasks

- [ ] Create a selection field for imperial or metric system
- [ ] Create a selection field for color theme
- [ ] Create a flavor text for developer info

**Comment by MonaHer** [comment]
LGTM :)

**Comment by JessicaLoers** [comment]
**Hi @makitango ✌️**

What feature exactly do you want to imply? The selection of the unit, or the possibility to switch your app to dark mode? Right now there are two features that you should definitely split into two user stories.

Settings itself is not really a feature at this point. 

Additionally, I would recommend that you revise your Acceptance Criteria. What happens when I make a selection as a user, for example setting the unit to "Metric"? 
How do I reach the settings? How can I exit/close them again? 

**If you have any questions, feel free to ask.**

**Comment by makitango** [comment]
> What feature exactly do you want to imply? The selection of the unit, or the possibility to switch your app to dark mode? Right now there are two features that you should definitely split into two user stories.

Splitting the features up, I agree on that!

> Settings itself is not really a feature at this point.

But how do I make this feature without a dedicated place to change the settings? As for getting there, I wanted to make it accessible via URL only until the latter feature of "Navbar in header", which is already listed.

> What happens when I make a selection as a user, for example setting the unit to "Metric"?

It would map the array again but only make the imperial sizes visible.

How do I reach the settings? How can I exit/close them again?

By clicking in the header which acts as a navigation bar, like in my 6th US.

**Comment by JessicaLoers** [comment]
> But how do I make this feature without a dedicated place to change the settings? As for getting there, I wanted to make it accessible via URL only until the latter feature of "Navbar in header", which is already listed.

In the first step, you would not need an extra page or something similar for the settings. You could make this setting directly on the overview of all airlines. 

What I want to say is that it's the settings are not the feature, but rather the **possibility to change the unit of the size of the luggage pieces**.

Here is an example:

**As an** airplane traveller 
**I want to** change the unit of my luggage size
**So that I** easily understand and compare luggage sizes without needing to convert between different measurement. 

> It would map the array again but only make the imperial sizes visible.

But where is it visible to the user? These are points that should be listed in the Acceptance Criteria. 

> By clicking in the header which acts as a navigation bar, like in my 6th US. But until then, only via URL

Unfortunately, this is not a good User Experience, probably the user will never find the way to the settings. I would suggest that you place the "unit change" feature on the overview page for now. 

Even if it doesn't seem like it, I don't want to make your life harder, but easier.  😁

**Comment by makitango** [comment]
> In the first step, you would not need an extra page or something similar for the settings. You could make this setting directly on the overview of all airlines.

You mean like a popup or overlay, like with filter and sort?

> As an airplane traveller
> I want to change the unit of my luggage size
> So that I easily understand and compare luggage sizes without needing to convert between different measurement.

Ah, now I get it!

> But where is it visible to the user? These are points that should be listed in the Acceptance Criteria.

By highlighting the active setting in green, right?

> Unfortunately, this is not a good User Experience, probably the user will never find the way to the settings. I would suggest that you place the "unit change" feature on the overview page for now.

Yes, it was a fear I also had. So maybe one button for all filter, sort and options combined? I am thinking about using a hamburger menu on the top left or use something like a universal round button in the center below to pop up all the things to change.

> Even if it doesn't seem like it, I don't want to make your life harder, but easier. 😁

It doesn't seem like making it harder at all, you gave the perfect feedback by explaining how an item makes you feel, and then why. And you even give suggestions in part while not revealing a full solution. ;)

**Comment by makitango** [comment]
Updated!

**Comment by JessicaLoers** [comment]
**Hi @makitango ✌️**
Almost done. Just some suggestion to write the Acceptance Criteria in more detail. 

- the default luggage size unit is set to Metric
- there are two button to change the unit of the luggage size measurement between Metric and Imperial units
- Upon selection of a new unit, it should immediately convert and display the luggage size in the newly chosen measurement unit
- If user selects the Metric system, luggage size should be displayed in centimeters (cm) and/or meters (m)
- If the user selects the Imperial system, luggage size should be displayed in inches (") and/or feet (')
- It should clearly label the measurement unit next to the displayed luggage size to avoid confusion

Because it's been such a hard road, I'm going to mark the US as approved, but it would be super cool if you expanded the Acceptance Criteria.

**Comment by makitango** [comment]
Just one addition: 
> If the user selects the Imperial system, luggage size should be displayed in inches (") and/or feet (')
I would keep feet out of it since it's only hand luggage sizes and all the websites featuring this topic are also resorting to inch only. Surfboards are not in scope for nad luggage :D
