### ISSUE TITLE
My own bags section

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#4]
## Value proposition

As an airplane traveller
I want a feature that allows entering my bag dimensions
So I have my info at hand to know for which airlines to look for

## Description
![Image](https://user-images.githubusercontent.com/20736983/251479969-22245018-0264-492a-aff7-f5f11ce8e30d.png)

## Acceptance criteria

- [ ] There has to be one section for each item
- [ ] Each item has length, width and depth
- [ ] Each item can be added, updated or deleted

## Tasks

- [ ] Create a button for adding a bag
- [ ] Create a form to enter the data
- [ ] Create a button to update the bag
- [ ] Create a form to update the data
- [ ] Create a button to deleta a bag
- [ ] Create a form to update the data
- [ ] Create a LocalStorage for the entered data

**Comment by sebastianwel** [comment]
Hey Dominik, 
as I know from previous feedback on US  I think this US is a bit too large with all that functionalities you want to add. 
I would recommend to split it into more US for the CRUDs and to iteratively implement these functions. 

E.g.:
- button for creating + the form + local storage 
- and so on... 
- Maybe you can put update and delete together since I think deletion is quite a small function. 

Hope that won't be a problem, cheers!

**Comment by makitango** [comment]
> I would recommend to split it into more US for the CRUDs and to iteratively implement these functions.

Agreed. Will adjust

**Comment by makitango** [comment]
Updated

**Comment by vaupunkt** [comment]
lgtm!
will i only be able to add one bag and only one personal item or more in the future? :)

**Comment by makitango** [comment]
> will i only be able to add one bag and only one personal item or more in the future? :)

It says already in the title, HAND LUGGAGE :D
(no airline will allow 3 backpacks or trolleys as hand luggage I reckon)
