### ISSUE TITLE
Filter function

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#5]
## Value proposition

As an airplane traveller
I want a feature that allows filtering airlines by free cabin bag or by my bag dimensions
So that I can only see the airlines which allow my bags as hand luggage (or pay a surcharge to have them with me)

## Description
![Image](https://github.com/makitango/hand-luggage-ninja/assets/20736983/ca946514-3870-4da6-82d0-7fed86842c0c)

## Acceptance criteria
- [ ] Needs to incorporate the filter functionality in the same screen of sort
- [ ] filter 1 maps the list of airlines to only show the ones which match or exceed the sizes of the personal bags entered
- [ ] filter 2 maps the list of airlines to only show the ones with free cabin bags
- [ ] filter 3 shows the original airline list (default)

## Tasks
- [ ] filter 1: crate a mapping mechanism to get a new array based on the bag sizes
- [ ] filter 2: create a filter mechanism to only show the airlines whose freeCabinBag key is set to true
- [ ] filter 3: restore the original airline list

**Comment by ekat-br** [comment]
LGTM :)
