### ISSUE TITLE
Navbar in header

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#6]
## Value proposition

As a user
I want a navbar directly in the header
So that I can save space and I can have a long list while navigating to different sections of the app

## Description
![Image](https://user-images.githubusercontent.com/20736983/251496738-5a6256fd-d786-4970-beec-0334bb091db4.png)

## Acceptance criteria

- [ ] Uses an overlay so it can still be clear on which screen the user is

## Tasks

- [ ] Create a navigation bar component that replaces the header
- [ ] Create styling that features opacity
