### ISSUE TITLE
Edit bags

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#7]
## Value proposition

As an airplane traveller
I want a feature that allows editing my bag dimensions
So I can correct a mistake from entering, change the dimensions when I get a new bag or change the bag I use for travelling.

## Description
![Image](https://user-images.githubusercontent.com/20736983/252312875-f342b9c4-f370-4954-9620-21dc19fef9a9.png)

## Acceptance criteria

- [ ] The dimensions should be displayed right after hitting the save button

## Tasks

- [ ] Create a button for editing a bag
- [ ] Create a form to enter the data
- [ ] Create a button to cancel
- [ ]  Create a button to save it

**Comment by AliaksandraNovikava** [comment]
Hey Dominic,
I would suggest adding more acceptance criteria for this user story. 

- When clicking on the "Edit" button "Cancel" and "Save" buttons should be displayed instead of "Edit" and "Delete" buttons.
- The user should be able to modify the bag dimensions.
- The dimensions should be displayed right after hitting the save button.
- Upon saving, "Edit" and "Delete" buttons should be displayed instead of "Cancel" and "Save" buttons.
- Clicking on the "Cancel" button should discard any changes made to the bag dimensions and return the user to the previous view that should remain unchanged.

**Comment by makitango** [comment]
Added the acceptance critera, many thanks!
Also removed the delete button which is in fact part of a later US.

**Comment by matschi3** [comment]
looks good now 👍🏼 nice detailed description, i like that.

What you could think about for future:
use the same Form for `entering` new data as well as `editing` the same data giving your form defaultData
