### ISSUE TITLE
Delete bags

### ISSUE THREAD

**Issue by makitango** [makitango/hand-luggage-ninja#8]
## Value proposition

As an airplane traveller
I want a feature that allows deleting my bag dimensions
So I can mirror my situation when I sell a bag or stop using one

## Description
![Image](https://user-images.githubusercontent.com/20736983/252314118-6d5c9238-1ee7-4f43-87b8-c7447d937605.png)

## Acceptance criteria

- [x] The deletion will take part after 10 seconds unless cancelled

## Tasks

- [x] Create a button for deleting a bag
- [x] Create a function to undo the delete for 10 seconds
